### ISSUE TITLE
Decoder seems to not include last block?

### ISSUE THREAD

**Issue by cinderblock** [meszaros-lajos-gyorgy/node-pkware#4]
I'm working on moving my project from `implode-decoder` to your `node-pkware`.

I have previously gotten a decoder working with `implode-decoder` and so wanted to start with getting a side-by-side comparison of your decoders, before moving onto using the encoder as we've talking about in #3.

In the process, I think I've found a bug with your decoder.

Checkout my [project](https://github.com/cinderblock/EWD/tree/wip-node-pkware). Quick setup:

```bash
git clone --branch wip-node-pkware https://github.com/cinderblock/EWD.git
cd EWD
mkdir -p samples
wget -cq --directory-prefix samples https://github.com/cinderblock/3-Phase-Driver/raw/master/Driver.{ewprj,ms14} &
npx npm@7 install
npm run dev -- --verbose samples/*
```

You will see the last 100 characters of output that were common to both. However, the output of your decoder is `7072` bytes shorter than expected, which the reference decoder gets correctly.

PS, I wrote some TypeScript types for you. Feel free to include them in your sources. I'd be happy to make a separate PR for those if you like.

**Comment by cinderblock** [comment]
Well, I think I found the intended API. There is a `decoder._state.onInputFinished` that wants to be called with its own callback to get the last bit of data. I've updated the branch to reflect this. However this API feels wrong, like I'm doing something silly, because I'm accessing what I assume is private `_state`. Yet it seems to decode correctly...

Looking into the code, this looks like it might be the intended design. I see a [`this._flush = state.onInputFinished` in `explode.js`](https://github.com/meszaros-lajos-gyorgy/node-pkware/blob/v1.0.0-beta.1/src/explode.js#L329).

I'm curious, why are you using this API? It seems to me that a "stream" format would be more appropriate. What do you think?

**Comment by meszaros-lajos-gyorgy** [comment]
Hi! `_state` is indeed private, but I need it to be accessible from the outside so that I can run my unit tests. `onInputFinished` should be called by the readstream as soon as it runs out of data.

Regarding streams `explode` and `implode` returns only a handler function, which can be given to a transform stream, but the algorithms need to know when the input data finishes, so I rely on injecting a callback function to the transform stream's `_flush` callback: https://nodejs.org/api/stream.html#stream_transform_flush_callback. It should be hooked up automatically as soon as the first bits of data: https://github.com/meszaros-lajos-gyorgy/node-pkware/blob/master/src/explode.js#L330

The above mentioned `this._flush = ...` part is a bit tricky, because this doesn't refer to the context of `explode` or `implode`, but to the transform stream that the callback will be added to.

The reason I go with `explode` and `implode` only returning a handler function and not a fully initialized transport stream is that I want to apply higher order functions to it before adding it to a pipeline. For example Arx Fatalis' files have a non-compressed and compressed part, which I need to split before utilizing explode or implode.

**Comment by meszaros-lajos-gyorgy** [comment]
I've checked your code and you are calling the handler given by explode() directly, which should be haded over to a transport stream. I already have a small example in the readme on how to decompress buffers in the style of streams: https://github.com/meszaros-lajos-gyorgy/node-pkware#decompressing-buffer-with-no-offset-into-a-buffer

```javascript
const { Readable } = require('stream')
const { explode, stream } = require('node-pkware')
const { through, streamToBuffer } = stream

Readable.from(buffer) // buffer is of type Buffer with compressed data
  .pipe(through(explode()))
  .pipe(
    streamToBuffer(decompressedData => {
      // decompressedData holds the decompressed buffer
    })
  )
```

**Comment by cinderblock** [comment]
Ah, I see. I failed to look at the docs thoroughly. Thank you.

Why did you choose to use this alternate stream library over Node.js's Stream library?

**Comment by meszaros-lajos-gyorgy** [comment]
Please check, if you can make your code work with the example I provided and if so, then I'll close the ticket. I might create a simple function version of pkware explode once I'm done with the remaning things for implode.

**Comment by cinderblock** [comment]
Sure. Any thoughts on incorporating TypeScript types in what you publish? I'm happy to make a PR just for those.

**Comment by meszaros-lajos-gyorgy** [comment]
I'm not a fan of typescript, but I don't deny that it would be a useful addition to many javascript developers. If you can add typescript support to the codebase, then I would be very greatful and as always, PRs are welcome!
